- name: catalogue configure
  hosts: catalogue
  become: yes
  tasks:
  - name: disable nodejs default version
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: Enable Node.js 20 module stream and install nodejs package
    ansible.builtin.dnf:
      name: "@nodejs:20"
      state: present
  
  - name: Create a system user 
    ansible.builtin.user:
        name: roboshop
        comment: "roboshop system user" 
        group: myapp          # Set primary group to 'myapp'
        shell: /sbin/nologin  # Prevents interactive login
        create_home: no       # Prevents creating a home directory
        system: yes           # Designates as a system account
        state: present    
  - name: Create a directory 
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: Download catalogue code 
    ansible.builtin.get_url:
      url: curl -o /tmp/catalogue.zip https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /app
  
  - name: unzip the code 
    ansible.builtin.unarchive:
      src: /app
      dest: /tmp/catalogue.zip
      remote_src: yes

  - name: copying System service file
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: daemon_reload
    ansible.builtin.systemd_service:
      state: restarted
      daemon_reload: true
      name: catalogue
      
  - name: Enable and start catalogue
    ansible.builtin.systemd_service:
      name: catalogue
      state: started
      enabled: true

  - name: copying mongo.repo
    ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

  - name: install mongdb-mongosh 
    ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

  