- name: mysql configure
  hosts: mysql
  become: yes

  tasks:
  - name: install mysql server
    ansible.builtin.dnf:
      name: mysql-server
      state: present


  - name: Set root password roboshop
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1

# - name: Set MySQL root password
#   community.mysql.mysql_user:
#     name: root
#     host: localhost
#     password: RoboShop@1
#     login_unix_socket: /var/lib/mysql/mysql.sock

  - name: enable and start mysql
    ansible.builtin.service:
      name: mysql
      state: restarted
      enabled: yes